### ISSUE TITLE
Support .NET 6 w/ Minimal API

### ISSUE THREAD

**Issue by h3rmanj** [Intility/Intility.Logging#29]
.NET 6 introduced a `WebApplicationBuilder`, which contains properties for `Host` (`IHostBuilder`) and `WebHost` (`IWebHostBuilder`).

Until now, we've targeted the [`IHostBuilder`](https://github.com/Intility/Intility.Logging/blob/main/src/Intility.Logging.AspNetCore/HostBuilderExtensions.cs#L20), and used it's [`ConfigureWebHostDefaults`](https://github.com/Intility/Intility.Logging/blob/main/src/Intility.Logging.AspNetCore/HostBuilderExtensions.cs#L20) to set up Sentry, which only targets the `IWebHostBuilder`.

Since the new `WebApplicationBuilder` gives us direct access to the `IWebHostBuilder`, it now throws an error if we try to configure it via the `IHostBuilder.CreateWebHostDefaults`.

@emilkje and me came to two possible solutions;

1. Create an extension for `IWebHostBuilder` exclusively, as Sentry only has extension methods for it. Serilog supports both `IHostBuilder` and `IWebHostBuilder`, so it shouldn't be a problem. The only downside is I don't know if we'll miss out on anything if we don't target `IHostBuilder`.
2. Create an extension for `WebApplicationBuilder`. This way we can still configure Serilog directly to `IHostBuilder`, and target `IWebHostBuilder` for Sentry.

I'll gladly do this when we've researched which option is the best one.

**Comment by emilkje** [comment]
Proposed fix #31

**Comment by h3rmanj** [comment]
Closing seeing as it works with minimal APIs with no apparent issues.
