### ISSUE TITLE
Sentry Environments

### ISSUE THREAD

**Issue by h3rmanj** [Intility/Intility.Logging#47]
Using only the Serilog extension when adding Sentry hooks, the Environment need to be specified, otherwise it defaults to `production`. Currently there is no way for consumers to specify this other than specifying the Sentry:Environment variable manually in the configuration, when it should be connected/dependent on the built in environment name.

We could either hard-code an addition to the sentry config environment based on `ASPNETCORE_ENVIRONMENT` or `NETCORE_ENVIRONMENT`, although that doesn't seem safe.

I think the best way currently is to accept an optional `environment` string in our `UseSentry` extension;  
`public static ILoggerBuilder UseSentry(this ILoggerBuilder builder, string configSection = "Sentry", string environment = null)`

And then override the Environment setting when adding Sentry as a serilog output.

This would allow for consumers to optionally send in their environment from the web host builder;
```csharp
builder.Host.UseIntilityLogging((ctx, logging) =>
{
    logging.UseDefaultEnrichers()
        .UseElasticsearch()
        .UseSentry(environment: builder.Environment.EnvironmentName);
});
```

Alternatively we could allow an action to UseSentry
```csharp
builder.Host.UseIntilityLogging((ctx, logging) =>
{
    logging.UseDefaultEnrichers()
        .UseElasticsearch()
        .UseSentry(config => {
          config.Environment = builder.Environment.EnvironmentName
        });
});
```

**Comment by emilkje** [comment]
Thanks for raising the issue. I share your concern and think the optional parameter on the extension is the way to go.
